In [2]:
import pandas as pd

In [7]:
data = pd.read_csv('./data.csv')
data

    name  age         city
0   John   23     New York
1  Alice   29  Los Angeles
2    Bob   35      Chicago

In [10]:
data = pd.read_csv('./cars.csv')
data

         country  cars_per_cap  drives_right
0  United States           809          True
1      Australia           731         False
2          Japan           588         False
3          India            18         False
4         Russia           200          True
5        Morocco            70          True
6          Egypt            45          True

In [12]:
country = data['country']
cars_per_cap = data['cars_per_cap']
drives_right = data['drives_right']
print(country)
print(cars_per_cap)
print(drives_right)
data = pd.read_csv('./cars.csv')

0    United States
1        Australia
2            Japan
3            India
4           Russia
5          Morocco
6            Egypt
Name: country, dtype: object
0    809
1    731
2    588
3     18
4    200
5     70
6     45
Name: cars_per_cap, dtype: int64
0     True
1    False
2    False
3    False
4     True
5     True
6     True
Name: drives_right, dtype: bool

In [14]:
print(data[['country', 'cars_per_cap']])

         country  cars_per_cap
0  United States           809
1      Australia           731
2          Japan           588
3          India            18
4         Russia           200
5        Morocco            70
6          Egypt            45

In [18]:
data

         country  cars_per_cap  drives_right
0  United States           809          True
1      Australia           731         False
2          Japan           588         False
3          India            18         False
4         Russia           200          True
5        Morocco            70          True
6          Egypt            45          True

In [17]:
data.loc[country == 'United States']

         country  cars_per_cap  drives_right
0  United States           809          True

In [ ]:
data.iloc[:2]